  require('./dpki_setup');
  require('./rp_setup');
  require('./idp_setup');
  require('./as_setup');
  require('./as_service_setup');
//   require('./proxy_setup');
  require('./create_identity');
//   require('./ndid');
//   require('./dpki');
  require('./add_accessor');
  require('./revoke_accessor');
//   require('./verify_identity');
  require('./data_request');
//   require('./create_request');
//   require('./idp_response');
//   require('./as_data_response');
//   require('./token');
//   require('./ndid_disable_enable');