version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: ndidplatform/base-test
    working_directory: /ndid/test
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            ~/.yarn/bin/yarn
      - run: git clone https://github.com/ndidplatform/smart-contract.git /go/src/github.com/ndidplatform/smart-contract
      - run:
          name: 'Install smart-contract dependencies (todo: use a dep management solution?)'
          command: |
            cd /go/src/github.com/ndidplatform/smart-contract/abci
            dep ensure
            go install
      - run: git clone https://github.com/ndidplatform/api.git /ndid/api
      - run:
          name: 'Install api dependencies'
          command: |
            cd /ndid/api
            npm install

      #region Start IDP node
      - run:
          name: idp-abci
          command: |
            (
              cd /go/src/github.com/ndidplatform/smart-contract
              CALLBACK_URI=http://localhost:3000/callback go run abci/server.go tcp://127.0.0.1:46000
            ) 2>&1 | tee -a /ndid/logs/idp-abci.log
          background: true
      - run:
          name: idp-tendermint
          command: |
            (
              cd /go/src/github.com/ndidplatform/smart-contract
              tendermint --home ./config/tendermint/IdP unsafe_reset_all
              tendermint --home ./config/tendermint/IdP node --consensus.create_empty_blocks=false
            ) 2>&1 | tee -a /ndid/logs/idp-tendermint.log
          background: true
      #endregion
      #region Start RP node
      - run:
          name: rp-abci
          command: |
            (
              cd /go/src/github.com/ndidplatform/smart-contract
              CALLBACK_URI=http://localhost:3001/callback go run abci/server.go tcp://127.0.0.1:46001
            ) 2>&1 | tee -a /ndid/logs/rp-abci.log
          background: true
      - run:
          name: rp-tendermint
          command: |
            (
              cd /go/src/github.com/ndidplatform/smart-contract
              tendermint --home ./config/tendermint/RP unsafe_reset_all
              tendermint --home ./config/tendermint/RP node --consensus.create_empty_blocks=false
            ) 2>&1 | tee -a /ndid/logs/rp-tendermint.log
          background: true
      #endregion
      - run: node waitForLog --file=/ndid/logs/idp-abci.log --text=Commit --count=2
      - run: node waitForLog --file=/ndid/logs/rp-abci.log --text=Commit --count=2

      #region Start IDP API
      - run:
          name: Initialize Dev Key
          command: |
            cd /ndid/api
            npm run initDevKey
      - run:
          name: idp-api
          command: |
            (
              cd /ndid/api
              ROLE=idp \
              MQ_CONTACT_IP=127.0.0.1 \
              MQ_BINDING_PORT=5555 \
              ABCI_APP_CALLBACK_PORT=3000 \
              SERVER_PORT=8080 \
              npm start
            ) 2>&1 | tee -a /ndid/logs/idp-api.log
          background: true
      - run:
          name: rp-api
          command: |
            (
              cd /ndid/api
              ROLE=rp \
              ABCI_APP_CALLBACK_PORT=3001 \
              MQ_CONTACT_IP=127.0.0.1 \
              MQ_BINDING_PORT=5556 \
              SERVER_PORT=8081 \
              npm start
            ) 2>&1 | tee -a /ndid/logs/rp-api.log
          background: true
      - run: node waitForLog --file=/ndid/logs/idp-abci.log --text=Commit --count=3
      - run: node waitForLog --file=/ndid/logs/rp-abci.log --text=Commit --count=3
      #endregion

      - run:
          name: Init sample identity
          command: |
            sleep 5
            curl --header 'Content-Type: Application/json' -X POST --data " {\"namespace\": \"uid\", \"identifier\" : \"123456\", \"secret\":\"MAGIC\", \"accessor_type\":\"awesome-type\", \"accessor_key\":\"awesome-key\",\"accessor_id\":\"some-awesome-accessor\"}"  http://localhost:8080/identity

      - run:
          name: Run Newman
          command: |
            newman run relying_party.postman_collection.json --reporters junit
      #region Post-test
      - store_test_results:
          path: /ndid/test/newman
      - store_artifacts:
          path: /ndid/logs
          destination: logs
      - store_artifacts:
          path: /ndid/test/newman
      #endregion
